version: '3.1'
services:
  mavenwebapp:
    image: ravshan1972/maven-web-application:VERSION
    restart: always
    ports:
      - 9090:8080
    networks:
      - mavenappbridge
networks:
  mavenappbridge:
    name: mavenappbridge
    driver: bridge
    #external: true    
